import os
import openai
import sqlite3
import requests
import json
import argparse
import sys
from datetime import datetime
from typing import Dict, List

from outlook_manager import API_KEY 

CLIENT_ID = "fde8d6d4-cb6f-4ad5-862f-0ab740a0bec8"
CLIENT_SECRET = "gux8Q~2BYmIH_mqOHS8fh-s6fUqh~CYsNHMnebJg"
REFRESH_TOKEN = "M.C558_BAY.0.U.-Cl5YV9G25zFECodweaq*1R0rdbGcpsAEZIUccTZRaVf!ohL*wbpr99tgp5k*UQqD5ynbzs*hYLhmw4PvVT2xzp9quo!YFYlTMKJF6T97xMD1uaCn81!uO3cVpZ3Ynao960bYN9U!5w2OU5cbCQmqclJdMzCPFGKZz6GdkTm09V0wNeSXiEPcp3zUfBTeGK1xT2krgQibt73zalWWr!*Z03uL6VMiAleClbntbhx7Bjx0KyEFyh5FFIq89PL51mMZOX*cGuoB1vtz8PrPMzdYkQxHzmjo3*lst4zB!MbZEhw75QMoxmNSRFK0ZTYl7lHlcJc4WVieSXVGv8617th7W1aQqmRX2oJLrJ0KXSZT!XvnM5WdMale9q!uY008V4!jJGeo!Ajh8zmMluZLsC6ZsLQ$"


openai.api_key = API_KEY
_call_openai_with_instruction = None

# for classification of individual messages
def classify_message(subject: str, body: str, model: str = 'gpt-4o-mini') -> Dict[str, str]:
    """Use OpenAI to classify a single email into priority/category/phrase/description."""
    system = (
        "Provide a JSON object with keys: 'priority' (HIGH, MEDIUM, LOW), "
        "'category' (WORK, SOCIAL, SUGGESTION, SPAM, AUTOMATED), 'phrase' (short summary), "
        "WORK is related to job tasks and administrative information. This is when someone directly asks you for something that needs to be done, or is very important to complete."
        "SOCIAL is related to friends/family planning and organizing, and is strictly non-work related. This is when someone is asking to meet up, or share personal news, or anything that is not work related but still important to keep track of."
        "AUTOMATED is for messages that are automatically generated and don't require direct action, but may still be important to be aware of. This includes things like receipts, account notifications, or any message that is clearly generated by a system rather than a person. They can often be LOW priority unless they contain important information."
        "ANY message that feels like it was generated by a bot or system rather than a human should be categorized as AUTOMATED, even if it is asking for something to be done OR contains a suggestion. \n"
        "SUGGESTION is related to potential future benefits (e.g. networking, sales, etc) or activities that could be beneficial to do but aren't strictly required."
        "SPAM is junk email. Anything that seems like it could be a scam, phishing, or just generally unwanted should be categorized as SPAM. \n"
        "LOW priority is for emails that don't require immediate attention, or unimportant, scammy or automated messages. They can often addressed at a later time. Anything automated or bot-generated should be LOW. \n"
        "MEDIUM priority is for emails that are important but not urgent. They should be addressed in a timely manner, but don't require immediate action. This might include emails sent out to larger groups but NOT bot-generated emails. \n" \
        "HIGH priority is for emails that require immediate attention. They are often time-sensitive and may have significant consequences if not addressed promptly. \n"
        "Any messages that feels like SCAM or PHISHING should be categorized as LOW, even if they are technically asking for something to be done. \n"
        "and 'description' (one sentence explaining the email). \n" 
        "Return only the JSON."
    )

    user = "Subject: {subject}\nBody: {body}\n".format(subject=subject, body=body)

    try:
        resp = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=0.1,
            max_tokens=400,
        )
        resp = resp['choices'][0]['message']['content'].strip()
        print(resp, file=sys.stderr)
        clean = resp.strip().removeprefix("```json").removesuffix("```").strip()
        return json.loads(clean)
    except Exception as e:
        print(f"Error calling OpenAI API: {e}", file=sys.stderr)
        print("Error in message classification. Defaulting to LOW priority WORK category.", file=sys.stderr)
        return {"priority": "LOW", "category": "WORK", "phrase": subject or "", "description": body[:150]}

GRAPH_MESSAGES_URL = "https://graph.microsoft.com/v1.0/me/messages"

def refresh_outlook_token(client_id = CLIENT_ID, client_secret = CLIENT_SECRET, refresh_token = REFRESH_TOKEN) -> str:
    url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
    
    data = {
        'client_id': client_id,
        'refresh_token': refresh_token,
        'grant_type': 'refresh_token',
        'scope': 'https://graph.microsoft.com/.default'
    }
    
    response = requests.post(url, data=data)
    tokens = response.json()
    
    if 'access_token' in tokens:
        print("Token refreshed successfully!")
        return tokens['access_token']
    else:
        print("Error refreshing token:", tokens.get('error_description'))
        return None


def _ensure_columns(conn: sqlite3.Connection) -> None:
    """Add the columns to ``messages`` if they do not already
    exist.  The operation is idempotent.
    """
    columns_to_add = [
        "category TEXT",
        "priority TEXT",
        "summary_phrase TEXT",
        "description TEXT"
    ]
    
    for column_def in columns_to_add:
        try:
            conn.execute(f"ALTER TABLE messages ADD COLUMN {column_def}")
            conn.commit()
        except sqlite3.OperationalError as exc:
            pass
    


def _fetch_all_messages() -> List[Dict]:
    """Retrieve messages from inbox and sent items only (excluding trash/deleted).
    
    Fetches from both inbox and sentitems folders, following @odata.nextLink
    pages until the service runs out of results.
    """
    headers = {"Authorization": f"Bearer {ACCESS_TOKEN}"}
    all_messages: List[Dict] = []
    
    # Fetch from inbox
    inbox_url = "https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages"
    while inbox_url:
        resp = requests.get(inbox_url, headers=headers)
        if resp.status_code != 200:
            raise RuntimeError(f"Graph request failed {resp.status_code}: {resp.text}")
        data = resp.json()
        all_messages.extend(data.get("value", []))
        inbox_url = data.get("@odata.nextLink")
    
    # Fetch from sent items
    sent_url = "https://graph.microsoft.com/v1.0/me/mailFolders/sentitems/messages"
    while sent_url:
        resp = requests.get(sent_url, headers=headers)
        if resp.status_code != 200:
            raise RuntimeError(f"Graph request failed {resp.status_code}: {resp.text}")
        data = resp.json()
        all_messages.extend(data.get("value", []))
        sent_url = data.get("@odata.nextLink")
    
    return all_messages


# ingestion

def ingest_all(db_path: str = "extracted.db", json_path: str = "data.json", quiet: bool = False) -> None:
    """Fetch every mail message, classify it and insert into the database.

    Spam messages are skipped; everything else is stored in the shared
    ``messages`` table with a ``category`` value.
    """
    try:
        conn = sqlite3.connect(db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY,
                source TEXT,
                thread_key TEXT,
                display_name TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS messages (
                id INTEGER PRIMARY KEY,
                source TEXT,
                source_msg_key TEXT,
                source_rowid INTEGER,
                conversation_id INTEGER,
                sender TEXT,
                is_from_me INTEGER,
                sent_at_utc TEXT,
                text TEXT,
                category TEXT,
                priority TEXT,      
                summary_phrase TEXT, 
                description TEXT   
            )
        """)

        try:
            _ensure_columns(conn)
        except sqlite3.OperationalError:
            pass
        
        if not quiet:
            print("fetching messages from Outlook...")
        messages = _fetch_all_messages()
        if not quiet:
            print(f"retrieved {len(messages)} messages")

        json_items = []

        for msg in messages:
            subj = msg.get("subject", "")
            sender = msg.get("from", {}).get("emailAddress", {}).get("address", "")
            sender_obj = msg.get("from", {}).get("emailAddress", {})
            sender_name = sender_obj.get("name", "Unknown")
            body = msg.get("body", {}).get("content", "")
            read_status = msg.get("isRead", False)
            ai_summary = classify_message(subj, body)


            if ai_summary["category"] == "Spam":
                continue

            thread_key = msg.get("conversationId") or msg.get("id")

            cursor = conn.execute(
                "INSERT INTO conversations (source, thread_key, display_name) VALUES (?, ?, ?)",
                ("outlook", thread_key, subj)
            )
            conv_id = cursor.lastrowid


            sent_at_utc = msg.get("sentDateTime") or msg.get("receivedDateTime")

            rowid = int(datetime.fromisoformat(sent_at_utc.rstrip("Z")).timestamp())

            new_id = f"todo_{cursor.lastrowid}"

            if json_path:
                json_entry = {
                    "platform":"outlook", 
                    "id": msg.get("id"),
                    "title": (ai_summary["phrase"][:57] + "...") if len(ai_summary["phrase"]) > 60 else ai_summary["phrase"],
                    "phrase": f"{ai_summary['phrase']} ({sender_name})",
                    "description": ai_summary["description"],
                    "body": f"From {sender_name}: {ai_summary['description']}",
                    "date": sent_at_utc[:10] if sent_at_utc else "",
                    "timestamp": sent_at_utc,
                    "notes": f"From: {sender_name} | Subject: {subj}",
                    "source": "Outlook",
                    "sourceIcon": "📧",
                    "priority": ai_summary["priority"].upper(),
                    "category": ai_summary["category"].upper(),
                    "read": read_status
                }
                json_items.append(json_entry)

            conn.execute("""
                    INSERT INTO messages (
                        source, source_msg_key, source_rowid, conversation_id, sender, 
                        is_from_me, sent_at_utc, text, category, priority, summary_phrase, description
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    "outlook", 
                    msg.get("id"), 
                    rowid,
                    conv_id, 
                    sender, 
                    0,
                    sent_at_utc,
                    body, 
                    ai_summary["category"], 
                    ai_summary["priority"], 
                    ai_summary["phrase"], 
                    ai_summary["description"]
                ))

        conn.commit()
        conn.close()

        if json_path:
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump({"notifications": json_items}, f, indent=2)

        if not quiet:
            print("ingestion complete")
    except Exception as e:
        if not quiet:
            print(f"ingest_all error: {e}", file=sys.stderr)

def _export_threads_to_datafile(messages: List[Dict], data_path: str = "mobile_gmail/data.json") -> None:
    """Replace the `threads` key in a local JSON file with a simplified
    view of the given Outlook messages.

    This mirrors what the mobile app expects when it loads
    ``data.json`` at startup so that a successful login will immediately
    surface Outlook mail in the UI.
    """
    import json

    # group messages by full sender name (first + last if available)
    grouped: Dict[str, List[Dict]] = {}
    for msg in messages:
        sender = msg.get("from", {}).get("emailAddress", {}).get("name") or \
                 msg.get("from", {}).get("emailAddress", {}).get("address") or "Unknown"
        grouped.setdefault(sender, []).append(msg)

    threads = []
    # helper to ask the model for summary and open items for a list of messages
    def _summarize_group(person: str, msgs: List[Dict]) -> Dict:
        if not _call_openai_with_instruction:
            return {"summary": "", "open_items": []}
        # build a simple text blob containing subjects and previews
        parts = []
        for m in msgs:
            subj = m.get("subject") or "(no subject)"
            preview = m.get("bodyPreview") or ""
            preview = (preview[:800] + "...") if len(preview) > 800 else preview
            parts.append(f"Subject: {subj}\nPreview: {preview}")
        items_text = "\n\n".join(parts)
        instruction = (
            "You are given a set of email snippets exchanged with a single person. "
            "Return a JSON object with two keys: 'summary' (a 1-3 sentence overview of the communication) "
            "and 'open_items' (an array of objects; each object should have 'item' and a 'deadline' field, deadline may be null if none)."
        )
        try:
            resp = _call_openai_with_instruction(items_text, instruction, model="gpt-4o-mini")
            return json.loads(resp)
        except Exception:
            return {"summary": "", "open_items": []}

    for person, msgs in grouped.items():
        # pick most recent message for metadata
        sorted_msgs = sorted(msgs, key=lambda x: x.get("receivedDateTime") or "", reverse=True)
        latest = sorted_msgs[0]
        contact = person.split(" ")[0]
        avatar = contact[:1].upper()
        report = _summarize_group(person, msgs)
        threads.append({
            "id": latest.get("id"),
            "contact": person,
            "avatar": avatar,
            "avatarColor": "#888888",
            "lastMessage": latest.get("subject") or "",
            "timestamp": latest.get("receivedDateTime") or latest.get("sentDateTime"),
            "source": "Outlook",
            "sourceIcon": "📧",
            "unread": sum(0 if m.get("isRead") else 1 for m in msgs),
            "summary": report.get("summary", ""),
            "openItems": report.get("open_items", []),
            "relatedDates": [],
        })

    try:
        with open(data_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        data = {}
    data["threads"] = threads
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)



if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--token", help="Microsoft access token to use")
    parser.add_argument("--quiet", action="store_true", help="suppress log output, only emit JSON")
    args = parser.parse_args()

    try:
        if args.token:
            ACCESS_TOKEN = args.token
        
        else:
            ACCESS_TOKEN = refresh_outlook_token()
            if not ACCESS_TOKEN:
                raise RuntimeError("Failed to obtain access token.")
        # Fetch only inbox emails
        headers = {"Authorization": f"Bearer {ACCESS_TOKEN}"}
        inbox_url = "https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages"

        ingest_all()
        # notifications is a list of actionable to-dos (already written to data.json by filter_emails)
        #print(f"Summary from OpenAI: {notifications}", file=sys.stderr)
        # Print notifications as JSON for frontend/Node.js
        #print(json.dumps({"notifications": notifications}))
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({"notifications": []}))
