import os
import openai
import sqlite3
import requests
import json
import argparse
import sys
import re
from datetime import datetime
from typing import Dict, List

from mobile_gmail.outlook_manager import API_KEY 

CLIENT_ID = "fde8d6d4-cb6f-4ad5-862f-0ab740a0bec8"
CLIENT_SECRET = "gux8Q~2BYmIH_mqOHS8fh-s6fUqh~CYsNHMnebJg"
REFRESH_TOKEN = "M.C558_BAY.0.U.-Cl5YV9G25zFECodweaq*1R0rdbGcpsAEZIUccTZRaVf!ohL*wbpr99tgp5k*UQqD5ynbzs*hYLhmw4PvVT2xzp9quo!YFYlTMKJF6T97xMD1uaCn81!uO3cVpZ3Ynao960bYN9U!5w2OU5cbCQmqclJdMzCPFGKZz6GdkTm09V0wNeSXiEPcp3zUfBTeGK1xT2krgQibt73zalWWr!*Z03uL6VMiAleClbntbhx7Bjx0KyEFyh5FFIq89PL51mMZOX*cGuoB1vtz8PrPMzdYkQxHzmjo3*lst4zB!MbZEhw75QMoxmNSRFK0ZTYl7lHlcJc4WVieSXVGv8617th7W1aQqmRX2oJLrJ0KXSZT!XvnM5WdMale9q!uY008V4!jJGeo!Ajh8zmMluZLsC6ZsLQ$"
ACCESS_TOKEN = None

openai.api_key = API_KEY
_call_openai_with_instruction = None

URL_RE = re.compile(
    r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"
)

def extract_urls(text: str) -> List[str]:
    urls = []
    for m in URL_RE.finditer(text):
        u = m.group(1).strip().rstrip(".,;:!\"]}")
        if u.startswith("www."):
            u = "https://" + u
        urls.append(u)
    seen = set()
    out = []
    for u in urls:
        if u not in seen:
            seen.add(u)
            out.append(u)
    return out

# for classification of individual messages
def classify_message(subject: str, body: str, model: str = 'gpt-4o-mini') -> Dict[str, str]:
    """Use OpenAI to classify a single email into priority/category/phrase/description."""
    system = (
        "Provide a JSON object with keys: 'priority' (HIGH, MEDIUM, LOW), "
        "'category' (WORK, SOCIAL, SUGGESTION, SPAM, AUTOMATED), "
        "'phrase' (a short action-oriented phrase describing what the recipient needs to do or be aware of — "
        "write it as an imperative action if action is required, e.g. 'Reply to meeting invite', "
        "'Review budget proposal', 'Confirm attendance for Friday dinner'; "
        "for automated/informational emails write a brief awareness note, e.g. 'New sign-in detected'), "
        "WORK is related to job tasks and administrative information. This is when someone directly asks you for something that needs to be done, or is very important to complete."
        "SOCIAL is related to friends/family planning and organizing, and is strictly non-work related. This is when someone is asking to meet up, or share personal news, or anything that is not work related but still important to keep track of."
        "AUTOMATED is for messages that are automatically generated and don't require direct action, but may still be important to be aware of. This includes things like receipts, account notifications, or any message that is clearly generated by a system rather than a person. They can often be LOW priority unless they contain important information."
        "ANY message that feels like it was generated by a bot or system rather than a human should be categorized as AUTOMATED, even if it is asking for something to be done OR contains a suggestion. \n"
        "SUGGESTION is related to potential future benefits (e.g. networking, sales, etc) or activities that could be beneficial to do but aren't strictly required."
        "SPAM is junk email. Anything that seems like it could be a scam, phishing, or just generally unwanted should be categorized as SPAM. \n"
        "LOW priority is for emails that don't require immediate attention, or unimportant, scammy or automated messages. They can often addressed at a later time. Anything automated or bot-generated should be LOW. \n"
        "MEDIUM priority is for emails that are important but not urgent. They should be addressed in a timely manner, but don't require immediate action. This might include emails sent out to larger groups but NOT bot-generated emails. \n" \
        "HIGH priority is for emails that require immediate attention. They are often time-sensitive and may have significant consequences if not addressed promptly. \n"
        "Any messages that feels like SCAM or PHISHING should be categorized as LOW, even if they are technically asking for something to be done. \n"
        "and 'description' (one sentence explaining the email). \n" 
        "Return only the JSON."
    )

    user = "Subject: {subject}\nBody: {body}\n".format(subject=subject, body=body)

    try:
        resp = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=0.1,
            max_tokens=400,
        )
        resp = resp['choices'][0]['message']['content'].strip()
        clean = resp.strip().removeprefix("```json").removesuffix("```").strip()
        return json.loads(clean)
    except Exception as e:
        print(f"Error calling OpenAI API: {e}", file=sys.stderr)
        print("Error in message classification. Defaulting to LOW priority WORK category.", file=sys.stderr)
        return {"priority": "LOW", "category": "WORK", "phrase": subject or "", "description": body[:150]}

GRAPH_MESSAGES_URL = "https://graph.microsoft.com/v1.0/me/messages"

def refresh_outlook_token(client_id: str | None = None, client_secret: str | None = None, refresh_token: str | None = None) -> str | None:
    client_id = client_id or os.getenv("MICROSOFT_CLIENT_ID") or CLIENT_ID
    client_secret = client_secret or os.getenv("MICROSOFT_CLIENT_SECRET")
    refresh_token = refresh_token or os.getenv("MICROSOFT_REFRESH_TOKEN")

    if not client_secret or not refresh_token:
        return None

    url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
    
    data = {
        'client_id': client_id,
        'refresh_token': refresh_token,
        'grant_type': 'refresh_token',
        'scope': 'https://graph.microsoft.com/.default'
    }
    
    response = requests.post(url, data=data)
    tokens = response.json()
    
    if 'access_token' in tokens:
        print("Token refreshed successfully!")
        return tokens['access_token']
    else:
        print("Error refreshing token:", tokens.get('error_description'))
        return None


def resolve_access_token(cli_token: str | None) -> str | None:
    if cli_token:
        return cli_token

    env_token = os.getenv("OUTLOOK_ACCESS_TOKEN")
    if env_token:
        return env_token

    return refresh_outlook_token()


def _ensure_columns(conn: sqlite3.Connection) -> None:
    """Add the columns to ``messages`` if they do not already
    exist.  The operation is idempotent.
    """
    columns_to_add = [
        "category TEXT",
        "priority TEXT",
        "summary_phrase TEXT",
        "description TEXT",
        "sender_name TEXT"
    ]
    
    for column_def in columns_to_add:
        try:
            conn.execute(f"ALTER TABLE messages ADD COLUMN {column_def}")
            conn.commit()
        except sqlite3.OperationalError as exc:
            pass
    


def _fetch_all_messages() -> List[Dict]:
    """Retrieve messages from inbox and sent items only (excluding trash/deleted).
    
    Fetches from both inbox and sentitems folders, following @odata.nextLink
    pages until the service runs out of results.
    """
    headers = {"Authorization": f"Bearer {ACCESS_TOKEN}"}
    all_messages: List[Dict] = []
    
    # Fetch from inbox
    inbox_url = "https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages"
    while inbox_url:
        resp = requests.get(inbox_url, headers=headers)
        if resp.status_code != 200:
            raise RuntimeError(f"Graph request failed {resp.status_code}: {resp.text}")
        data = resp.json()
        all_messages.extend(data.get("value", []))
        inbox_url = data.get("@odata.nextLink")
    
    # Fetch from sent items
    sent_url = "https://graph.microsoft.com/v1.0/me/mailFolders/sentitems/messages"
    while sent_url:
        resp = requests.get(sent_url, headers=headers)
        if resp.status_code != 200:
            raise RuntimeError(f"Graph request failed {resp.status_code}: {resp.text}")
        data = resp.json()
        all_messages.extend(data.get("value", []))
        sent_url = data.get("@odata.nextLink")
    
    return all_messages


# ingestion

def ingest_all(db_path: str = "extracted.db", json_path: str = "data.json", quiet: bool = False) -> None:
    """Fetch every mail message, classify it and insert into the database.

    Spam messages are skipped; everything else is stored in the shared
    ``messages`` table with a ``category`` value.
    """
    try:
        conn = sqlite3.connect(db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY,
                source TEXT,
                thread_key TEXT,
                display_name TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS messages (
                id INTEGER PRIMARY KEY,
                source TEXT,
                source_msg_key TEXT,
                source_rowid INTEGER,
                conversation_id INTEGER,
                sender TEXT,
                sender_name TEXT,
                is_from_me INTEGER,
                sent_at_utc TEXT,
                text TEXT,
                category TEXT,
                priority TEXT,      
                summary_phrase TEXT, 
                description TEXT   
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS extracted_links (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                url TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT (datetime('now'))
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS extracted_attachments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                filename TEXT,
                mime_type TEXT,
                original_path TEXT,
                created_at TEXT NOT NULL DEFAULT (datetime('now'))
            )
        """)

        try:
            _ensure_columns(conn)
        except sqlite3.OperationalError:
            pass
        
        # Remove all existing Outlook content from the database before re-ingesting
        conn.execute("PRAGMA foreign_keys = ON;")
        conn.execute("DELETE FROM extracted_links WHERE message_id IN (SELECT id FROM messages WHERE source = 'outlook')")
        conn.execute("DELETE FROM extracted_attachments WHERE message_id IN (SELECT id FROM messages WHERE source = 'outlook')")
        conn.execute("DELETE FROM conversations WHERE source = 'outlook'")
        conn.execute("DELETE FROM messages WHERE source = 'outlook'")
        conn.commit()
        
        if not quiet:
            print("fetching messages from Outlook...")
        messages = _fetch_all_messages()
        if not quiet:
            print(f"retrieved {len(messages)} messages")

        json_items = []

        for msg in messages:
            subj = msg.get("subject", "")
            sender = msg.get("from", {}).get("emailAddress", {}).get("address", "")
            sender_obj = msg.get("from", {}).get("emailAddress", {})
            sender_name = sender_obj.get("name", "Unknown")
            body = msg.get("body", {}).get("content", "")
            read_status = msg.get("isRead", False)
            ai_summary = classify_message(subj, body)
            
            if ai_summary["category"].upper() == "SPAM":
                continue
            
            if ai_summary["category"].upper() == "SPAM":
                continue

            thread_key = msg.get("conversationId") or msg.get("id")

            cursor = conn.execute(
                "INSERT INTO conversations (source, thread_key, display_name) VALUES (?, ?, ?)",
                ("outlook", thread_key, subj)
            )
            conv_id = cursor.lastrowid


            sent_at_utc = msg.get("sentDateTime") or msg.get("receivedDateTime")

            rowid = int(datetime.fromisoformat(sent_at_utc.rstrip("Z")).timestamp())

            new_id = f"todo_{cursor.lastrowid}"

            if json_path:
                is_automated = ai_summary["category"].upper() == "AUTOMATED"
                raw_phrase = ai_summary["phrase"]
                display_phrase = f"[AUTOMATED] {raw_phrase}" if is_automated else raw_phrase
                truncated_title = (display_phrase[:57] + "...") if len(display_phrase) > 60 else display_phrase
                json_entry = {
                    "platform":"outlook", 
                    "id": msg.get("id"),
                    "title": truncated_title,
                    "phrase": f"{display_phrase} ({sender_name})",
                    "description": ai_summary["description"],
                    "body": f"From {sender_name}: {ai_summary['description']}",
                    "date": sent_at_utc[:10] if sent_at_utc else "",
                    "timestamp": sent_at_utc,
                    "notes": f"From: {sender_name} | Subject: {subj}",
                    "source": "Outlook",
                    "sourceIcon": "📧",
                    "priority": ai_summary["priority"].upper(),
                    "category": ai_summary["category"].upper(),
                    "read": read_status
                }
                json_items.append(json_entry)

            cursor = conn.execute("""
                    INSERT INTO messages (
                        source, source_msg_key, source_rowid, conversation_id, sender, sender_name,
                        is_from_me, sent_at_utc, text, category, priority, summary_phrase, description, account_key
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'outlook_user')
                """, (
                    "outlook", 
                    msg.get("id"), 
                    rowid,
                    conv_id, 
                    sender,
                    sender_name,
                    0,
                    sent_at_utc,
                    body, 
                    ai_summary["category"], 
                    ai_summary["priority"], 
                    ai_summary["phrase"], 
                    ai_summary["description"]
                ))
            message_id = cursor.lastrowid
            
            # Extract and insert links
            for url in extract_urls(body):
                conn.execute(
                    "INSERT INTO extracted_links(message_id, url) VALUES(?, ?)", 
                    (message_id, url)
                )
            
            # Extract and insert attachments
            for attachment in msg.get("attachments", []):
                filename = attachment.get("name", "Unknown File")
                mime_type = attachment.get("contentType", "application/octet-stream")
                attachment_id = attachment.get("id", "")
                conn.execute(
                    "INSERT INTO extracted_attachments(message_id, filename, mime_type, original_path) VALUES(?, ?, ?, ?)",
                    (message_id, filename, mime_type, f"outlook_attachment_id:{attachment_id}")
                )

        conn.commit()
        conn.close()

        if json_path:
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump({"notifications": json_items}, f, indent=2)

        if not quiet:
            print("ingestion complete")
    except Exception as e:
        if not quiet:
            print(f"ingest_all error: {e}", file=sys.stderr)


def _extract_event_from_email(
    subject: str, body: str, email_sent_datetime: str, model: str = "gpt-4o-mini"
) -> dict | None:
    """Use OpenAI to detect if an email mentions a specific future event with a date/time.

    ``email_sent_datetime`` should be the send date of the email (not today) so that
    relative day-words like 'Friday' or 'next Monday' are resolved correctly relative
    to when the email was written.

    Returns a dict with keys title, start, end, location, description if an event
    is found, or None if the email contains no clear upcoming event.
    """
    system = (
        f"The email was sent on (UTC): {email_sent_datetime}\n"
        "You are an assistant that extracts calendar-worthy event information from emails. "
        "When resolving relative date/time words (e.g. 'Friday', 'next Monday', 'tomorrow', "
        "'this weekend'), resolve them relative to the EMAIL SEND DATE above, NOT today's date. "
        "If the email references a specific event that has a date and/or time "
        "(e.g. a meeting, appointment, deadline, party, call, interview, flight, etc.), "
        "return a JSON object with these keys:\n"
        "  'title': short name for the event\n"
        "  'start': ISO 8601 datetime string (or date string if time unknown)\n"
        "  'end': ISO 8601 datetime string (empty string if unknown)\n"
        "  'location': location string (empty string if unknown)\n"
        "  'description': one sentence describing the event\n"
        "If the email does NOT contain a specific event with a clear date/time "
        "reference, return exactly: {\"event\": false}\n"
        "Return ONLY valid JSON, no extra text."
    )
    user = f"Subject: {subject}\nBody: {body[:2000]}\n"

    try:
        resp = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=0.1,
            max_tokens=300,
        )
        content = resp["choices"][0]["message"]["content"].strip()
        clean = content.removeprefix("```json").removesuffix("```").strip()
        parsed = json.loads(clean)
        if parsed.get("event") is False or not parsed.get("start"):
            return None
        return parsed
    except Exception as e:
        print(f"Error extracting event from email: {e}", file=sys.stderr)
        return None


def ingest_calendar_items(
    db_path: str = "extracted.db",
    json_path: str = "data.json",
    quiet: bool = False,
) -> None:
    """Populate the 'events' key in data.json AND the calendar_events table in
    extracted.db from two sources:

    1. Outlook Calendar : events fetched from the Graph calendarView API.
    2. Outlook Email    : emails scanned by OpenAI for date/time references that
       imply a future event.

    Rows are upserted by event id so re-running is safe.
    The data.json 'notifications' key written by ingest_all() is preserved.
    """
    try:
        now_utc = datetime.utcnow()
        now_str = now_utc.strftime("%Y-%m-%d %H:%M UTC")
        # Look up to 1 year ahead for calendar events
        end_utc = now_utc.replace(year=now_utc.year + 1)
        headers = {
            "Authorization": f"Bearer {ACCESS_TOKEN}",
            "Prefer": 'outlook.timezone="Pacific Standard Time"'
        }

        # ------------------------------------------------------------------
        # Set up / migrate extracted.db
        # ------------------------------------------------------------------
        conn = sqlite3.connect(db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS calendar_events (
                id          TEXT PRIMARY KEY,
                source      TEXT,
                title       TEXT,
                start_utc   TEXT,
                end_utc     TEXT,
                date        TEXT,
                location    TEXT,
                organizer   TEXT,
                attendees   TEXT,
                is_all_day  INTEGER DEFAULT 0,
                description TEXT,
                email_subject TEXT,
                email_date  TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS extracted_dates (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                message_id TEXT,
                raw_span TEXT,
                resolved_date TEXT,
                parsed_at_utc TEXT
            )
        """)
        conn.commit()
        
        # Remove all existing Outlook calendar/email events before re-ingesting
        conn.execute("DELETE FROM calendar_events WHERE source IN ('outlook_calendar', 'outlook_email')")
        conn.execute("DELETE FROM extracted_dates WHERE message_id LIKE 'outlook_cal_%'")
        conn.commit()

        json_events: List[Dict] = []

        calendar_url = (
            "https://graph.microsoft.com/v1.0/me/calendarView"
            f"?startDateTime={now_utc.strftime('%Y-%m-%dT%H:%M:%SZ')}"
            f"&endDateTime={end_utc.strftime('%Y-%m-%dT%H:%M:%SZ')}"
            "&$orderby=start/dateTime"
            "&$top=100"
        )

        calendar_events: List[Dict] = []
        while calendar_url:
            resp = requests.get(calendar_url, headers=headers)
            if resp.status_code != 200:
                if not quiet:
                    print(
                        f"Calendar API failed {resp.status_code}: {resp.text}",
                        file=sys.stderr,
                    )
                break
            data = resp.json()
            calendar_events.extend(data.get("value", []))
            calendar_url = data.get("@odata.nextLink")

        if not quiet:
            print(f"retrieved {len(calendar_events)} calendar events")

        for event in calendar_events:
            subject = event.get("subject", "No Title")
            start = event.get("start", {}).get("dateTime", "")
            end = event.get("end", {}).get("dateTime", "")
            location = event.get("location", {}).get("displayName", "")
            organizer = (
                event.get("organizer", {})
                .get("emailAddress", {})
                .get("name", "")
            )
            is_all_day = event.get("isAllDay", False)
            body_preview = event.get("bodyPreview", "")
            attendees = [
                a.get("emailAddress", {}).get("name", "")
                for a in event.get("attendees", [])
            ]

            json_events.append(
                {
                    "platform": "outlook_calendar",
                    "id": event.get("id", ""),
                    "title": subject,
                    "start": start,
                    "end": end,
                    "date": start[:10] if start else "",
                    "location": location,
                    "organizer": organizer,
                    "attendees": attendees,
                    "isAllDay": is_all_day,
                    "description": body_preview,
                    "source": "Outlook Calendar",
                    "sourceIcon": "📅",
                }
            )
            conn.execute("""
                INSERT OR REPLACE INTO calendar_events
                    (id, source, title, start_utc, end_utc, date, location,
                     organizer, attendees, is_all_day, description, email_subject, email_date)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                event.get("id", ""),
                "outlook_calendar",
                subject,
                start,
                end,
                start[:10] if start else "",
                location,
                organizer,
                json.dumps(attendees),
                1 if is_all_day else 0,
                body_preview,
                None,
                None,
            ))
            
            # also insert into extracted_dates for the UI summary endpoint
            conn.execute("""
                INSERT INTO extracted_dates (message_id, raw_span, resolved_date, parsed_at_utc)
                VALUES (?, ?, ?, ?)
            """, (
                f"outlook_cal_{event.get('id', '')}",
                subject,
                start,
                start
            ))

        # ------------------------------------------------------------------
        # pt 2: I want to scan emails for event mentions using OpenAI + current time
        # ------------------------------------------------------------------
        if not quiet:
            print("scanning emails for event mentions...")

        try:
            email_messages = _fetch_all_messages()
        except Exception as fetch_err:
            email_messages = []
            if not quiet:
                print(
                    f"could not fetch emails for event extraction: {fetch_err}",
                    file=sys.stderr,
                )

        for msg in email_messages:
            subj = msg.get("subject", "")
            body = msg.get("body", {}).get("content", "")
            sender_obj = msg.get("from", {}).get("emailAddress", {})
            sender_name = sender_obj.get("name", "Unknown")
            sent_at = msg.get("sentDateTime") or msg.get("receivedDateTime", "")

            # Resolve relative date words ("Friday", "tomorrow") against the
            # email's own send date, not the current wall-clock time.
            email_sent_str = (
                sent_at[:16].replace("T", " ") + " UTC" if sent_at else now_str
            )
            extracted = _extract_event_from_email(subj, body, email_sent_str)
            if extracted:
                ev_start = extracted.get("start", "")
                ev_end = extracted.get("end", "")
                json_events.append(
                    {
                        "platform": "outlook_email",
                        "id": msg.get("id", ""),
                        "title": extracted.get("title", subj),
                        "start": ev_start,
                        "end": ev_end,
                        "date": (ev_start or "")[:10],
                        "location": extracted.get("location", ""),
                        "organizer": sender_name,
                        "attendees": [],
                        "isAllDay": False,
                        "description": extracted.get("description", ""),
                        "source": "Outlook Email",
                        "sourceIcon": "📧",
                        "emailSubject": subj,
                        "emailDate": sent_at[:10] if sent_at else "",
                    }
                )
                conn.execute("""
                    INSERT OR REPLACE INTO calendar_events
                        (id, source, title, start_utc, end_utc, date, location,
                         organizer, attendees, is_all_day, description, email_subject, email_date)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    msg.get("id", ""),
                    "outlook_email",
                    extracted.get("title", subj),
                    ev_start,
                    ev_end,
                    (ev_start or "")[:10],
                    extracted.get("location", ""),
                    sender_name,
                    json.dumps([]),
                    0,
                    extracted.get("description", ""),
                    subj,
                    sent_at[:10] if sent_at else "",
                ))

                conn.execute("""
                    INSERT INTO extracted_dates (message_id, raw_span, resolved_date, parsed_at_utc)
                    VALUES (?, ?, ?, ?)
                """, (
                    msg.get("id", ""),
                    extracted.get("title", subj),
                    (ev_start or "")[:10],
                    ev_start
                ))

        if not quiet:
            print(
                f"event extraction complete: {len(json_events)} events total "
                f"({len(calendar_events)} from calendar, "
                f"{len(json_events) - len(calendar_events)} from emails)"
            )

        conn.commit()
        conn.close()

        # Part 3 – Merge into data.json under the 'events' key
        if json_path:
            try:
                with open(json_path, "r", encoding="utf-8") as f:
                    existing = json.load(f)
            except (FileNotFoundError, json.JSONDecodeError):
                existing = {}

            existing["events"] = json_events

            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(existing, f, indent=2)

    except Exception as e:
        if not quiet:
            print(f"ingest_calendar_items error: {e}", file=sys.stderr)








def generate_people_profiles(db_path: str = "extracted.db", json_path: str = "data.json", quiet: bool = False) -> None:
    """Generate person profiles from messages and calendar events.
    
    For each unique person (identified by email from senders, organizers, and attendees),
    creates a summary with their interaction history and upcoming events.
    Writes to both extracted.db (people table) and data.json (people key).
    """
    try:
        conn = sqlite3.connect(db_path)
        
        # Add sender_name column if it doesn't exist
        try:
            conn.execute("ALTER TABLE messages ADD COLUMN sender_name TEXT")
            conn.commit()
        except sqlite3.OperationalError:
            pass
        
        # Create people table
        conn.execute("""
            CREATE TABLE IF NOT EXISTS people (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT UNIQUE NOT NULL,
                name TEXT,
                summary TEXT,
                notification_count INTEGER DEFAULT 0,
                event_count INTEGER DEFAULT 0,
                created_at TEXT DEFAULT (datetime('now'))
            )
        """)
        conn.commit()
        
        # Extract unique people and merge by name/email match
        raw_people = []  # list of (email, name) tuples
        
        # From message senders (prefer sender_name over email)
        cursor = conn.execute("""
            SELECT DISTINCT sender, sender_name FROM messages 
            WHERE sender IS NOT NULL AND sender != ''
        """)
        for sender, sender_name in cursor.fetchall():
            if sender:
                name = sender_name if sender_name and sender_name != "Unknown" else sender
                raw_people.append((sender, name))
        
        # From calendar organizers
        cursor = conn.execute("""
            SELECT DISTINCT organizer FROM calendar_events
            WHERE organizer IS NOT NULL AND organizer != ''
        """)
        for (organizer,) in cursor.fetchall():
            if organizer:
                raw_people.append((organizer, organizer))
        
        # Merge people with matching email or name
        people_map = {}  # canonical_email -> canonical_name
        email_to_canonical = {}  # maps any email to canonical email
        name_to_canonical = {}  # maps any name to canonical email (for dedup by name)
        
        for email, name in raw_people:
            # Check if this email or name already maps to a person
            canonical_email = email_to_canonical.get(email) or name_to_canonical.get(name)
            
            if canonical_email:
                # Merge with existing person
                if name and name != "Unknown" and (name_to_canonical.get(name) is None):
                    name_to_canonical[name] = canonical_email
                if email not in email_to_canonical:
                    email_to_canonical[email] = canonical_email
            else:
                # New person
                canonical_email = email
                email_to_canonical[email] = canonical_email
                if name and name != "Unknown":
                    name_to_canonical[name] = canonical_email
                people_map[canonical_email] = name if name and name != "Unknown" else email
        
        # Build per-person notification and event lists
        people_data = {email: {"notifications": [], "events": []} for email in people_map}
        
        # Gather notifications per person using canonical emails
        cursor = conn.execute("""
            SELECT sender, category, priority, summary_phrase, description, sent_at_utc
            FROM messages
            WHERE sender IS NOT NULL AND sender != ''
            ORDER BY sent_at_utc DESC
        """)
        for sender, category, priority, phrase, description, sent_at in cursor.fetchall():
            canonical = email_to_canonical.get(sender)
            if canonical and canonical in people_data:
                people_data[canonical]["notifications"].append({
                    "category": category,
                    "priority": priority,
                    "phrase": phrase,
                    "description": description,
                    "date": sent_at[:10] if sent_at else ""
                })
        
        # Gather events per person using canonical emails
        cursor = conn.execute("""
            SELECT organizer, title, start_utc, location, description
            FROM calendar_events
            WHERE organizer IS NOT NULL AND organizer != ''
            ORDER BY start_utc DESC
        """)
        for organizer, title, start_utc, location, description in cursor.fetchall():
            canonical = name_to_canonical.get(organizer) or email_to_canonical.get(organizer)
            if canonical and canonical in people_data:
                people_data[canonical]["events"].append({
                    "title": title,
                    "date": start_utc[:10] if start_utc else "",
                    "location": location,
                    "description": description
                })
        
        # Clear existing people entries
        conn.execute("DELETE FROM people")
        conn.commit()
        
        json_people = []
        
        for email, name in people_map.items():
            notifications = people_data[email]["notifications"]
            events = people_data[email]["events"]
            
            # Generate summary from notifications if available
            if notifications:
                summary_items = [n.get("phrase", n.get("category", "Interaction")) for n in notifications[:3]]
                summary = f"Communicated about: {', '.join(summary_items)}"
            else:
                summary = f"Calendar contact"
            
            # Insert into database
            conn.execute("""
                INSERT INTO people (email, name, summary, notification_count, event_count)
                VALUES (?, ?, ?, ?, ?)
            """, (email, name, summary, len(notifications), len(events)))
            
            # Prepare JSON entry
            json_people.append({
                "email": email,
                "name": name,
                "summary": summary,
                "notificationCount": len(notifications),
                "eventCount": len(events),
                "recentNotifications": notifications[:5],
                "recentEvents": events[:5]
            })
        
        conn.commit()
        conn.close()
        
        # Write to data.json
        if json_path:
            try:
                with open(json_path, "r", encoding="utf-8") as f:
                    existing = json.load(f)
            except (FileNotFoundError, json.JSONDecodeError):
                existing = {}
            
            existing["people"] = json_people
            
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(existing, f, indent=2)
        
        if not quiet:
            print(f"generated profiles for {len(json_people)} people")
    
    except Exception as e:
        if not quiet:
            print(f"generate_people_profiles error: {e}", file=sys.stderr)


def outlook_ingest(
    access_token: str | None = None,
    db_path: str = "extracted.db",
    json_path: str = "data.json",
    quiet: bool = False,
) -> None:
    """Run full Outlook ingestion (messages, calendar/event extraction, people).

    Pass `access_token` from mobile_gmail/App.js sign-in to avoid personal refresh
    tokens. If `access_token` is omitted, falls back to environment/refresh flow.
    """
    global ACCESS_TOKEN

    ACCESS_TOKEN = resolve_access_token(access_token)
    if not ACCESS_TOKEN:
        raise RuntimeError(
            "No Outlook access token available. Pass access_token from mobile_gmail/App.js sign-in "
            "or set OUTLOOK_ACCESS_TOKEN."
        )

    ingest_all(db_path=db_path, json_path=json_path, quiet=quiet)
    ingest_calendar_items(db_path=db_path, json_path=json_path, quiet=quiet)
    generate_people_profiles(db_path=db_path, json_path=json_path, quiet=quiet)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--token", help="Microsoft access token to use")
    parser.add_argument("--quiet", action="store_true", help="suppress log output, only emit JSON")
    args = parser.parse_args()

    try:
        outlook_ingest(access_token=args.token, quiet=args.quiet)
        # notifications is a list of actionable to-dos (already written to data.json by filter_emails)
        #print(f"Summary from OpenAI: {notifications}", file=sys.stderr)
        # Print notifications as JSON for frontend/Node.js
        #print(json.dumps({"notifications": notifications}))
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({"notifications": []}))
